version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: web.Dockerfile
    ports:
    - "8000:8000"
    volumes:
    - ./data:/data
    env_file: []
    depends_on:
    - redis


  worker:
    build:
      context: .
      dockerfile: worker.Dockerfile
    command: celery -A app.tasks worker -l info
    volumes:
    - ./data:/data
    depends_on:
    - redis


  beat:
    build:
      context: .
      dockerfile: worker.Dockerfile
    command: celery -A app.tasks beat -l info --schedule /data/celerybeat-schedule
    volumes:
    - ./data:/data
    depends_on:
    - redis


  redis:
    image: redis:7-alpine
    ports:
    - "6379:6379"
    volumes:
    - redis-data:/data


volumes:
  redis-data: