services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - "8000:8000"
    volumes:
    - ./data:/data
    env_file: []
    depends_on:
    - redis


  worker:
    build: .
    command: celery -A app.celery_app worker -l info
    volumes:
    - ./data:/data
    depends_on:
    - redis


  beat:
    build:
      context: .
    command: celery -A app.celery_app beat -l info --schedule /data/celerybeat-schedule
    volumes:
    - ./data:/data
    depends_on:
    - redis


  redis:
    image: redis:7
    ports:
    - "6379:6379"


volumes:
  redis-data: